version: '3.8'

services:
  #databases
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - posgres_db_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
  
  #api Auth
  api_auth:
    build: 
      context: ./
      dockerfile: dockerfile
    env_file:
      - .env
    command: bash -c "while true; do sleep 1000; done"
    #command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8001:8000"
    depends_on:
      - postgres_db

volumes:
  posgres_db_data: