FROM python

WORKDIR /usr/src/app

RUN apt update && apt update -y
RUN apt install python3-pip python3-dev libpq-dev -y
RUN python3 -m pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt
